config/routes.rb
Rails.application.routes.draw do
  get 'orders/success'
  get 'orders/bought'
  get 'orders/sold'
  resources :listings
  devise_for :users
  root 'page#home'

  post "listings/:id/order", to: "listings#place_order", as: "place_order"

  get 'orders/success', to: 'orders#success'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_rich_text :description
  has_one_attached :picture

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :listing
  belongs_to :buyer
  belongs_to :seller
  belongs_to :buyer, foreign_key: "buyer_id", class_name: "User"
  belongs_to :seller, foreign_key: "seller_id", class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :listings       

  has_many :sold_orders, foreign_key: "seller_id", class_name: "Order" 
  has_many :bought_orders, foreign_key: "buyer_id", class_name: "Order"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: %i[ show edit update destroy place_order ]
  before_action :set_form_vars, only: %i[ new edit ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize_user, only: [:edit, :update, :destroy]

  # GET /listings or /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1 or /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings or /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user = current_user

    respond_to do |format|
      if @listing.save
        format.html { redirect_to listing_url(@listing), notice: "Listing was successfully created." }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1 or /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to listing_url(@listing), notice: "Listing was successfully updated." }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1 or /listings/1.json
  def destroy
    @listing.destroy

    respond_to do |format|
      format.html { redirect_to listings_url, notice: "Listing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def place_order
    Order.create(
      listing_id: @listing.id,
      seller_id: @listing.user_id,
      buyer_id: current_user.id
    )

    @listing.update(sold: true)

    redirect_to orders_success_path
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    def set_form_vars
      @categories = Category.all
    end
    
    # Display alert when listing does not belong to current_user
    def authorize_user
      if @listing.user_id != current_user.id
        flash[:alert] = "Unauthorised.  This listing belongs to someone else!"
        redirect_to listings_path
      end
    end

    # Only allow a list of trusted parameters through.
    def listing_params
      params.require(:listing).permit(:name, :description, :condition, :size, :price, :sold, :user_id, :category_id, :picture)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  
  def success
  end

  # Match current_user with bought_item users and display
  def bought
    @bought_items = current_user.bought_orders
  end

  # Match current_user with sold_item users and display
  def sold
    @sold_items = current_user.sold_orders
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end

  def success
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
    def format_condition(condition)
		words = condition.split("_").map do |word| 
			words.join(" ")
        end    
	end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rebornplants</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container"
    <%= render 'shared/nav' %>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>  

    <% if Rails.env.development? %>
    <% console %>
    <% end %>
  </body>
</html>

app/views/listings/_form.html.erb
<%= simple_form_for(@listing) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description, as: :rich_text_area %>
    <%= f.input :condition, collection: ["Need a lot of love", "Brown leaves", "Reasonably healthy", "Healthy", "Almost new", "New"] %>
    <%= f.input :size, collection: ["N/A", "Small", "Medium", "Large"] %>
    <%= f.input :price %>
    <%= f.association :category %>
    <%= f.input :picture, accept: "image/png, image/jpg, image/jpeg" %>

    </div>
  <div class="form-actions">
    <%= f.button :submit, class:"btn btn-success" %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<div style='float: right;'>
  <%= link_to 'Add Listing', new_listing_path, class:"btn btn-success btn-md" %>
  <%= link_to "Your Orders", orders_bought_path, class:"btn btn-success btn-md" %>
  <%= link_to "Your Sales", orders_sold_path, class:"btn btn-success btn-md" %>
</div>  

<h1>Listings</h1>

<%# Display card for each listing %>
<div class="row">
  <% @listings.each do |listing| %>
    <div class="col-md-4">
    <div class="card" style="width: 18rem;">

      <div>
        <%# Display default_image if no image is uploaded %>
        <% if listing.picture.attached? %>
        <%= image_tag listing.picture, class: "card-img-top img-fluid"%>
      <% else %>
        <%= image_tag "default_image.png", alt: listing.name, class: "card-img-top img-fluid" %>
        <% end %>
      </div>

      <div class="card-body">
          <h5 class="card-title"><%= listing.name %></h5>
          <p class="card-text" listing-description><%= listing.description %></p>
          <% if listing.sold %>
            <h6>SOLD</h6>
          <% end %>
          <%# Only display Edit or Delete button if listing.user_id matches current_user.id %>
          <%= link_to 'Show More', listing, class:"btn btn-success btn-sm" %>
            <% if current_user && current_user.id == listing.user_id %>
              <%= link_to 'Edit', edit_listing_path(listing), class:"btn btn-outline-warning btn-sm" %></td>
              <%= link_to 'Delete', listing, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-dark btn-sm" %></td>
            <% end %>
            
          <p>
          </p>
      </div>    
    </div> 
    </div>     
  <% end %> 
</div>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<div> 
  <% if @listing.picture.attached? %>
    <%= image_tag @listing.picture, alt: @listing.name, class:"show-image-size" %>
  <% else %>
    <%= image_tag "default_image.png", alt: @listing.name, class:"show-image-size" %>
  <% end %>
</div>

<%# UI behavior. If not sold display 'BUY' button if the listing.user_id does not match current_user.id %>
<% if @listing.sold %>
  <h4>SOLD</h4>
<% elsif current_user && current_user.id == @listing.user_id %>
  <h4>This item already belongs to you.</h4>
<% elsif current_user %>
  <%= button_to "BUY", place_order_path %>
<% else %>
  <h4>Please log in to make a purchase</h4>
<% end %>

<p>
  <strong>Name:</strong>
  <%= @listing.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @listing.condition %>
</p>

<p>
  <strong>Size:</strong>
  <%= @listing.size %>
</p>

<p>
  <strong>Price:</strong>
  <%= @listing.price %>
</p>

<p>
  <strong>Sold:</strong>
  <%= @listing.sold %>
</p>

<p>
  <strong>User:</strong>
  <%= @listing.user_id%>
</p>

<p>
  <strong>Category:</strong>
  <%= @listing.category_id %>
</p>

<%# Authorise current_user to Edit if user.id matches with listing.user_id %>
<% if current_user && current_user.id == @listing.user_id %>
  <%= link_to 'Edit', edit_listing_path(@listing), class:"btn btn-success btn-lg"%>
<% end %>

<%= link_to 'Back', listings_path, class:"btn btn-outline-success btn-lg" %>

app/views/orders/bought.html.erb
<h1>Items you have bought</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Condition</th>
      <th>Price</th>
      <th>Seller</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bought_items.each do |item| %>
      <tr>
        <td><%= item.listing.name %></td>
        <td><%= item.listing.description %></td>
        <td><%= item.listing.condition %></td>
        <td><%= number_to_currency(item.listing.price) %></td>
        <td><%= item.seller.username %></td>
        <td><%= item.listing.category.name %></td>
      </tr>
    <% end %>
  </tbody>
</table> 

app/views/orders/sold.html.erb
<h1>Items you have sold</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Condition</th>
      <th>Price</th>
      <th>Seller</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sold_items.each do |item| %>
      <tr>
        <td><%= item.listing.name %></td>
        <td><%= item.listing.description %></td>
        <td><%= item.listing.condition %></td>
        <td><%= number_to_currency(item.listing.price) %></td>
        <td><%= item.buyer.username %></td>
        <td><%= item.listing.category.name %></td>
      </tr>
    <% end %>
  </tbody>
</table> 

app/views/orders/success.html.erb
<h1>Congratulations on your order!</h1>

app/views/page/home.html.erb
<div class="jumbotron">
    <div class="row">
        <div class="col-md-6">
            <h1 class="display-4">Welcome to Reborn Plants!</h1>
            <h7>Reborn Plants was founded in June 2020, designed to connect plant lovers in Australia and give pre-loved plants a new home.</h7>
            <h7>This site is for plant owners who want their plant sold to a good home or buyers that have love and time to give.</h7>
            <hr class="my-4">
                <%= link_to "Listings", listings_path, class:"btn btn-outline-light btn-lg" %>
                <%= link_to 'Add Listing', new_listing_path, class:"btn btn-outline-light btn-lg" %>
            </p>  
        </div>

        <div class="col-md-6">
            <%=image_tag "home.png", alt: "urban jungle", class: "home-image" %>
        </div>
    </div>    
</div

app/views/shared/_nav.html.erb
<span>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" >
  <a class="navbar-brand" href="/">Reborn Plants</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
	  <li class="nav-item">
	  <%# Display Sign out if user is signed in otherwise display Sign up or Sign in links %>
	  <% if user_signed_in? %>
	  	<%= link_to "Sign out", destroy_user_session_path, method: :delete, class:"nav-link" %>
	  </li>
	  <li class="nav-item">
	  <% else %>
		<%= link_to "Sign up", new_user_registration_path, class:"nav-link" %>
	  </li>
	  <li>	
		<%= link_to "Sign in", new_user_session_path, class:"nav-link" %>
		<% end %>
      </li>
    </ul>
  </div>
</nav>
</span> 